"""Load the cleaned Superstore data into SQLite, run every query in
queries.sql, and write the results to RESULTS.md."""
import re
import sqlite3
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
DATA = HERE.parent / "data" / "superstore_clean.csv"


def load(conn):
    df = pd.read_csv(DATA)
    df.columns = [re.sub(r"[^a-z0-9]+", "_", c.lower()).strip("_") for c in df.columns]
    df = df.rename(columns={"monthname": "month_name"})
    df.to_sql("orders", conn, index=False)


def fmt(col, v):
    if pd.isna(v):
        return "—"
    if col in ("year", "month", "rnk", "cohort"):
        return str(int(v))
    if col.endswith(("sales", "value", "per_customer")):
        return f"{v:,.2f}"
    if float(v).is_integer() and not col.endswith(("_pct", "_days_to_ship")):
        return f"{int(v):,}"
    return format(float(v), ",")


def to_markdown(df):
    df = df.copy()
    for col in df.columns:
        if pd.api.types.is_numeric_dtype(df[col]):
            df[col] = df[col].map(lambda v, c=col: fmt(c, v))
    return df.to_markdown(index=False, disable_numparse=True)


def split_queries(sql):
    blocks = re.split(r"^-- (Q\d+: .+)$", sql, flags=re.M)
    return [(blocks[i], blocks[i + 1].strip()) for i in range(1, len(blocks), 2)]


def main():
    conn = sqlite3.connect(":memory:")
    load(conn)
    out = ["# SQL Analysis — Results", "",
           "Generated by `run_queries.py` from [`queries.sql`](queries.sql) "
           "on SQLite (table `orders`, 9,800 rows).", ""]
    for title, query in split_queries((HERE / "queries.sql").read_text(encoding="utf-8")):
        result = pd.read_sql_query(query, conn)
        out += [f"## {title}", "", "```sql", query, "```", "",
                to_markdown(result), ""]
        print(f"{title} -> {len(result)} rows")
    (HERE / "RESULTS.md").write_text("\n".join(out), encoding="utf-8")


if __name__ == "__main__":
    main()
